apiVersion: v1
kind: Service
metadata:
  name: blazork8s
spec:
  selector:
    app: blazork8s
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      nodePort: 30036 
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazork8s
spec:
  selector:
    matchLabels:
      app: blazork8s
  replicas: 2
  template:
    metadata:
      labels:
        app: blazork8s
    spec:
      containers:
        - name: blazork8s
          image: phillipsj/blazork8s:0.1.0
          ports:
            - containerPort: 80